- name: Install NFS utilities
  yum: name=nfs-utils

- name: Enable NFS service
  service: name=nfs-server enabled=yes state=started

- name: Create the NFS exports file
  copy: src=exports dest=/etc/exports
  notify: "Refresh NFS export"

