- name: Install xinetd
  yum: name=xinetd

- name: Install tftpd
  yum: name=tftp-server

- name: Install syslinux
  yum: name=syslinux

- name: Configure tftpd
  copy: src=tftp dest=/etc/xinetd.d/tftp
  notify: "Restart xinetd"

- name: Enable xinetd
  service: name=xinetd state=started enabled=yes


