- include_role: name=epel

- name: Disable SSH access
  firewalld: zone=public service=ssh state=disabled permanent=true immediate=true

- name: Disable NFS access from public zone
  firewalld: zone=public service=nfs state=disabled permanent=true immediate=true

- name: Configure private network
  copy: src=eno2.nmconnection dest=/etc/NetworkManager/system-connections/
  notify: "Restart network"

- name: Create cluster firewall zone
  shell: firewall-cmd --new-zone=cluster --permanent && firewall-cmd --zone=cluster --permanent --set-target=ACCEPT && firewall-cmd --reload
  args:
    creates: /etc/firewalld/zones/cluster.xml

- name: Add private network interface to the cluster zone
  firewalld: zone=cluster interface=eno2 state=enabled permanent=true immediate=true

- name: Packages needed for headnode
  yum: name={{item}}
  with_items:
          - rpcbind
          - net-tools
          - nmap
          - tcpdump
          - ipmitool
          - rsync
          - sqlite
          - bind-utils
          - vim

# Using docker for node image building instead
#- name: Configure dracut for creating pxe boot image
#  copy: src=dracut.conf dest=/etc/dracut.conf

- name: Perl modules
  yum: name=perl-{{item}}
  with_items:
          - Data-Dumper
          - HTML-Template
          - XML-Parser
          - libwww-perl
          - English
          - LDAP
          - DBD-SQLite
          - Time-HiRes
          - File-Copy

- name: Configure rsyslog collector
  copy: src=rsyslog.d-collector dest=/etc/rsyslog.d/collector.conf
  notify: "Restart rsyslog"

- name: Configure chronyd
  copy: src=chrony.conf dest=/etc/chrony.conf
  notify: "Restart chronyd"

- name: Set up headnode environment
  copy: src=env.sh dest=/etc/profile.d/

- name: Set the hostname
  copy: src=hostname dest=/etc/
  notify: "Set hostname"

- name: create resolver for headnode hostname
  copy: src=hosts dest=/etc/


