
- name: Enable SSH access
  firewalld: zone=public service=ssh state=enabled permanent=true immediate=true

- name: Disable NFS access from public zone
  firewalld: zone=public service=nfs state=disabled permanent=true immediate=true

- name: Configure private network
  copy: src=ifcfg-em1 dest=/etc/sysconfig/network-scripts/ifcfg-em1
  notify: "Restart network"

- name: Create cluster firewall zone
  shell: firewall-cmd --new-zone=cluster --permanent --set-target=ACCEPT && firewall-cmd --reload
  args:
    creates: /etc/firewalld/zones/cluster.xml

#- name: Add private network interface to the cluster zone
#  firewalld: zone=cluster interface=em1 state=enabled permanent=true immediate=true

- name: Packages needed for headnode
  yum: name={{item}}
  with_items:
          - rpcbind
          - net-tools
          - nmap

- name: Configure dracut for creating pxe boot image
  copy: src=dracut.conf dest=/etc/dracut.conf


- name: Perl modules
  yum: name=perl-{{item}}
  with_items:
          - Data-Dumper
          - HTML-Template
          - XML-Parser
          - libwww-perl

- name: Configure rsyslog collector
  copy: src=rsyslog.d-collector dest=/etc/rsyslog.d/collector.conf
  notify: "Restart rsyslog"

- name: Configure chronyd
  copy: src=chrony.conf dest=/etc/chrony.conf
  notify: "Restart chronyd"

