- include_role: name=slurm

- name: Create firewall zone for histamine cluster
  shell: firewall-cmd --new-zone=histamine --permanent && firewall-cmd --reload
  args:
    creates: /etc/firewalld/zones/histamine.xml

- name: Add histamine nodes
  firewalld: zone=histamine source={{ item }} state=enabled permanent=true immediate=true
  with_items:
          - 160.36.131.192
          - 160.36.131.191
          - 160.36.131.190
          - 160.36.131.189

- name: Allow slurm from histamine
  firewalld: zone=histamine port=6817-6818/tcp  state=enabled permanent=true immediate=true

- name: Allow slurm-srun from histamine
  firewalld: zone=histamine port=45000-46000/tcp  state=enabled permanent=true immediate=true


