- include_role: name=ganglia-gmetad
- include_role: name=webserver

- name: Install ganglia web front-end
  yum: 
        name: ganglia-web
  notify: "Restart Apache"

- name: Configure ganglia-web access
  copy: src=ganglia.conf dest=/etc/httpd/conf.d/
  notify: "Restart Apache"


