- hosts: hostname.icl.utk.edu
  remote_user: root
  handlers:
          - name: Restart SERVICE
            service: name=SERVICE state=restarted
  tasks:
          - name: Install PACKAGE
            yum: name=PACKAGE
          - name: Configure PACKAGE.conf
            template: src=PACKAGE.conf dest=/etc/PACKAGE.conf mode=0600
            notify: "Restart SERVICE"
          - name: Enable SERVICE
            service: name=SERVICE state=started enabled=yes

