
- name: Add "locate" command
  copy: src=locate dest=/usr/local/bin/locate mode=0755

- name: Add module_variants command
  copy: src=module_variants dest=/usr/local/bin/ mode=0755

- name: Remove mlocate package
  yum: name=mlocate state=absent

- name: Install postfix
  yum: name=postfix

- name: Set the root mail alias
  lineinfile:
    dest: /etc/aliases
    line: 'root: icl-it-verbose@icl.utk.edu'
  when: ansible_os_family == "RedHat"
  notify: 'Update mail aliases' 

- name: Disable SELinux
  copy: content="SELINUX=disabled" dest=/etc/selinux/config 

- name: Install packages
  yum:
    name: ['vim', 'tmux', 'psmisc', 'ipmitool', 'rsync']

- name: Install packages
  yum:
    name: ['bind-utils', 'OpenIPMI']
  when: ansible_os_family == "RedHat"

- name: Install policycoreutils-python
  yum:
    name: ['policycoreutils-python', 'deltarpm']
  when: (ansible_os_family == "RedHat") and (ansible_distribution_major_version < '8')

- name: Copy over MOTD
  copy: src=motd dest=/etc

