- include_role: name=docker

- name: Configure cluster network
  copy: src=ifcfg-em2 dest=/etc/sysconfig/network-scripts/
  notify: "ifup em2"

- name: Create cluster firewall zone
  shell: firewall-cmd --new-zone=cluster --permanent && firewall-cmd --zone=cluster --permanent --set-target=ACCEPT && firewall-cmd --reload
  args:
    creates: /etc/firewalld/zones/cluster.xml

- name: Add private network interface to the cluster zone
  firewalld: zone=cluster interface=em2 state=enabled permanent=true immediate=true

- include_role: name=nat

- name: Configure dnsmasq docker image
  copy: src=dnsmasq dest=/opt/ mode=preserve
  notify: "Reconfigure dnsmasq docker"

#- name: Configure nfs docker image
#  copy: src=nfs dest=/opt/ mode=preserve
#  notify: "Reconfigure nfs docker"

#- name: Configure slurm docker image
#  copy: src=slurm dest=/opt/ mode=preserve
#  notify: "Reconfigure slurm docker"

