#!/usr/bin/perl

use strict;
use warnings;
use Date::Parse 'str2time';

my $warn_days = 3;

my $date = (split /\t/, (`/usr/sbin/zfs get creation -H`)[-1])[2];
die "Error getting information on last backup.\n" unless defined $date;
my $time = str2time($date);
die "Error parsing last backup date.\n" unless defined $time;
my $days = int( (time - $time) / 3600 / 24);
die "Warning: Backup has not completed in $days days.\n" if $days >= $warn_days;

