#!/usr/bin/perl
# update links in /newton/files/pxelinux/pxelinux.cfg

use strict;
use warnings;
use lib "/newton/scripts";
use Newton;

my $dir = "/newton/files/pxelinux/pxelinux.cfg/";
chdir $dir;
my $nodes = Newton::nodes();

my %links = map {$_,1} grep {-l $_} glob('*');

for(@$nodes){
  my %info = %$_;
  next unless $info{role};
  my $config = "../$info{role}/config";
  unless(-e $config){
    warn "Role $info{role} doesn't exist for node $info{name}.";
    next;
    }
  my @hex = map {uc sprintf('%02x', $_)} split(/\./, $info{ip});
  my $linkname = join('', @hex);
  print `ln -sf $config $linkname`;
  delete $links{$linkname};
  }

for(keys %links){
  next if $_ eq 'default';
  print "Removing $_\n";
  unlink $_;
  }
