#!/usr/bin/perl
#
# 1. Add new nodes as admin and submit hosts
# 2. Apply complexes to hosts from complexes db table 
#

use strict;
use warnings;
use lib "/newton/scripts";
use Newton;
use Data::Dumper;

my $db = Newton::db();

my %existing_admin  = map {chomp;$_,1} `qconf -sh`;
my %existing_submit = map {chomp;$_,1} `qconf -ss`;
my $nodes = $db->selectcol_arrayref("SELECT name FROM addresses WHERE type='system'");

for(@$nodes){
  my $name = $_;
  unless( $existing_admin{$name}  ){ `qconf -ah $name` }
  unless( $existing_submit{$name} ){ `qconf -as $name` }
  }

# setting complex values
my $comp_data = $db->selectall_arrayref(
  'SELECT name,complex,value FROM addresses JOIN complexes ON addresses.nodeset=complexes.nodeset',
  );
for(@$comp_data){
  my ($name, $complex, $value) = @$_;
  `qconf -mattr exechost complex_values $complex=$value $name`;
  #`qconf -dattr exechost complex_values $complex $name`;
  }


