#!/usr/bin/perl

# Create a queue instance for each cluster queue and every node

use strict;
use warnings;
use Data::Dumper;

my @hosts = `qhost`;
my @queues = `qstat -g c`;
my %inst = map {/^(\S+\@[^\.]+)\S+\s+.+\d+\/(\d+)/;$1,$2} `qstat -f | grep B`;
#print Dumper \%inst;
for(@queues){
  chomp;
  my ($queue) = /^(\S+)\s+/;
  next unless $queue;
  next if $queue eq 'CLUSTER';
  for(@hosts){
    chomp;
    my ($host, $slots) = /^(\S+)\s+\S+\s+(\d+)/;
    next unless $host;
    next unless exists $inst{"$queue\@$host"};
    next if $inst{"$queue\@$host"} == $slots;
    my $cmd = "qconf -aattr queue slots \"[$host=$slots]\" $queue";
    print "$cmd\n";
    print `$cmd`;
    }
  }
  
