#!/usr/bin/perl

use strict;
use warnings;
use lib "/newton/scripts";
use Newton;

my $db = Newton::db();
my $sets = $db->selectcol_arrayref(
  'SELECT DISTINCT(nodeset) FROM addresses'
  );

for(@$sets){
  my $set = $_;
  next unless $set;
  my $nodes = $db->selectcol_arrayref(
    'SELECT name FROM addresses WHERE nodeset=?',
    undef, $set, 
    );
  next unless @$nodes;
  addset($set, $nodes);
  }


sub addset {
  my ($set, $nodes) = @_;
  my $tfile = '/tmp/.tfile-'.rand();
  open(OUT, "+>$tfile") or die $!;
  flock(OUT, 2);
  print OUT "group_name \@$set\n";
  print OUT "hostlist ",join(' ', @$nodes),"\n";
  close OUT;
  if(`qconf -shgrp \@$set`){
    `qconf -Mhgrp $tfile`;
    }
  else {
print "adding\n";
    `qconf -Ahgrp $tfile`;
    }
  #unlink $tfile;
  }


