#!/usr/bin/perl

# Make sure a given kernel module is loaded

use strict;
use warnings;
use lib '/usr/lib64/nagios/plugins';
use utils '%ERRORS';

my $module = shift @ARGV || die "Need name of kernel module";

open(IN, '/proc/modules') or die $!;
my ($line) = grep /^\Q$module\E\s+/, <IN>;
close IN;

finish('OK', "Kernel module '$module' is loaded.") if defined $line;
finish('CRITICAL', "Kernel module '$module' not loaded!");

sub finish {
  my ($code, $msg) = @_;
  print "Module $code: $msg\n";
  exit $ERRORS{$code};
  }
