- name: Refresh NFS export
  command: /usr/sbin/exportfs -r

- name: Restart NFS service
  service: name=nfs state=restarted

- name: Restart statd service
  service: name=rpc-statd state=restarted

- name: Reconfigure lockd service
  command: /usr/sbin/sysctl fs.nfs.nlm_tcpport=32888 fs.nfs.nlm_udpport=32888
  notify: "Restart NFS service"
