- include_role: name=docker

- name: Configure docker subuid
  copy: src=subuid dest=/etc/subuid

- name: Configure docker subgid
  copy: src=subgid dest=/etc/subgid

- name: Configure docker namespaces
  copy: src=daemon.json dest=/etc/docker/daemon.json
  notify: "Restart docker"

- name: Enable docker namespaces
  shell: grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"

- name: Modify sysctl user.max_user_namespaces
  sysctl: name=user.max_user_namespaces value=10

