- name: Install dnsmasq
  yum: name=dnsmasq

- name: Install dnsmasq-utils
  yum: name=dnsmasq-utils

- name: Configure dnsmasq
  copy: src=dnsmasq.conf dest=/etc/
  notify: "Restart dnsmasq"

- name: Enable dnsmasq
  service: name=dnsmasq state=started enabled=yes

