- name: Install dnsmasq
  yum: name=dnsmasq

- name: Install dnsmasq-utils
  yum: name=dnsmasq-utils

- name: Create PXE boot directory
  file: 
    path: /cluster/pxe
    state: directory
    recurse: true

- name: Configure dnsmasq
  copy: src=dnsmasq.conf dest=/etc/
  notify: "Restart dnsmasq"

- name: Enable dnsmasq
  service: name=dnsmasq state=started enabled=yes

