- include_role: name=epel

- name: Install slurmctld
  yum: name=slurm-slurmctld

- name: Create munge key
  command: /usr/sbin/create-munge-key 
  args:
          creates: /etc/munge/munge.key

- name: Enable munge service
  service: name=munge state=started enabled=yes

- name: Create slurm user
  user: name=slurm createhome=no local=yes system=yes group=daemon

- name: Create slurm directories
  file: path={{item}} state=directory owner=slurm group=daemon
  loop:
    - /var/spool/slurm
    - /var/log/slurm

- name: Configure slurm
  copy: src=slurm.conf dest=/etc/slurm/ force=false
  notify: "Restart slurmctld"

- name: Configure slurm cgroups
  copy: src=cgroup.conf dest=/etc/slurm/cgroup.conf
  notify: "Restart slurmctld"

- name: Enable slurmctld
  service: name=slurmctld state=started enabled=yes

