- name: Install EPEL
  yum: name=epel-release

- name: Install Slurm
  yum: name={{item}}
  with_items:
        - slurm
        - slurm-contribs
        - slurm-devel
        - slurm-pam_slurm
        - slurm-perlapi
        - slurm-slurmctld
        - slurm-slurmd

- name: Slurm dependencies
  yum: name={{item}}
  with_items:
          - gcc
          - mariadb-server
          - mariadb-devel
          - munge
          - munge-libs
          - munge-devel
          - rng-tools
          - openssl
          - openssl-devel 
          - pam-devel
          - numactl 
          - numactl-devel 
          - hwloc 
          - hwloc-devel 
          - lua 
          - lua-devel 
          - readline-devel 
          - rrdtool-devel 
          - ncurses-devel 
          - man2html 
          - libibmad 
          - libibumad
          - munge-devel
          - munge-libs
          - perl-ExtUtils-MakeMaker
          - mailx

#- name: Create munge user
#  user: name=munge createhome=no local=yes system=yes uid=997

- name: Create munge key
  command: /usr/sbin/create-munge-key 
  args:
          creates: /etc/munge/munge.key

- name: Enable munge service
  service: name=munge state=started enabled=yes

- name: Create slurm user
  user: name=slurm createhome=no local=yes system=yes group=daemon

- name: Create slurm directories
  file: path={{item}} state=directory owner=slurm
  with_items:
          - /etc/slurm
          - /var/spool/slurmd
          - /var/run/slurm

- name: Configure slurm
  copy: src=slurm.conf dest=/etc/slurm/slurm.conf
  notify: "Restart slurmctld"

- name: Configure slurm cgroups
  copy: src=cgroup.conf dest=/etc/slurm/cgroup.conf
  notify: "Restart slurmctld"

- name: Enable slurmctld
  service: name=slurmctld state=started enabled=yes

- name: Enable slurmd
  service: name=slurmd state=started enabled=yes

