
- name: Enable the firewall
  service: name=firewalld state=started enabled=yes

- name: Set the ICL network source
  firewalld: zone=internal source=160.36.131.0/24  permanent=true state=enabled immediate=true
