- name: Script file for implementing system modifications for perf counters
  copy: src=uncore.sh dest=/opt/uncore.sh mode=755
- name: Cron to implement KNL system changes on boot
  cron: 
    name: "Enable "
    job: "/opt/uncore.sh"
    special_time: reboot

- name : Cron to implement system changes periodically
  cron:
    name: "uncore events periodic"
    job: "/opt/uncore.sh"
    minute: 1
    hour: "*"
