#!/bin/bash -e

NAME=ganglia-web


docker build -t $NAME .
docker stop $NAME
docker rm $NAME

docker run --name $NAME \
   -d --restart=unless-stopped \
   -v ganglia:/var/lib/ganglia \
   -p 127.0.0.1:80:80 \
   $NAME

