- name: Copy cron script
  copy: 
    src: sync_os_install_files
    dest: /etc/cron.daily/
    mode: 755

- name: Add boot entry
  copy: src=50_install dest=/etc/grub.d/50_install mode=755
  notify: 
    - Update grub config
    - Update grub-efi config

