#!/usr/bin/perl

# Warn when the download speed gets too low

use strict;
use warnings;
use lib '/usr/lib64/nagios/plugins';
use utils '%ERRORS';

my $url = 'https://citr.utk.edu/test.dat';

my ($size) = grep {defined} map {/Content-Length: (\d+)/i;$1} `curl -sI $url`;
unless(defined $size){
  finish('WARNING', 'Failure to get file download size!');
}

my $t0 = time;
`curl -s -o /dev/null $url`;
$t0 = time - $t0;
if($t0 < 1){
  finish('WARNING', 'Error downloading file!');
}

my $speed = int(8*$size/$t0/1024/1024);  # Mbit/sec

finish('OK', "$speed Mbit/sec") if $speed > 100;
finish('WARNING', "$speed Mbit/sec!");

sub finish {
  my ($code, $msg) = @_;
  print "Bandwidth $code: $msg\n";
  exit $ERRORS{$code};
  }
