#!/bin/bash -e

if [ $USER != "root" ]; then
   echo Running as root
   sudo -i $0 $@
   exit
fi

set -x

NAME=$1
VARIANT=${2:-base}
BASEDIR=$(cluster_basedir)
DOCKER=$BASEDIR/nodes/$NAME/docker
DEST=$BASEDIR/nodes/$NAME/images/$VARIANT
DATE=`date '+%F-%T'`
ROOTFS=$DEST/rootfs-$DATE

if [[ -z "$NAME" || ! -d $DOCKER || ! -d $DEST ]]; then
	echo "Please provide a valid node image name"
	exit 1
fi

docker build --progress=plain -t temp \
	--ulimit nofile=1024000:1024000 \
	--build-context etc=/etc \
	--build-context munge=/etc/munge/ \
	--build-context slurm=/etc/slurm/ \
	--build-context ansible=$BASEDIR/ansible \
	--build-context common=$BASEDIR/nodes/common \
	--build-arg VARIANT=$VARIANT \
	$DOCKER
docker remove temp || true
docker run -it --name temp temp sleep 0
mkdir -p $ROOTFS
cd $ROOTFS
docker export temp | tar -x

headnode=`host headnode | awk '{print $4}'`
echo -e "search cluster\nnameserver $headnode" > etc/resolv.conf

cp -a /etc/ssh/ssh_host_rsa* etc/ssh/
chmod 600 etc/ssh/ssh_host*key
cat /root/.ssh/*.pub >> root/.ssh/authorized_keys

cd ..
rm -f rootfs
ln -sf $ROOTFS rootfs
ln -sf rootfs/boot/vmlinuz-* kernel
ln -sf rootfs/boot/init*.img initrd
touch $ROOTFS/$NAME-$DATE
echo Success!

