#!/bin/bash -e

if [ $USER != "root" ]; then
   echo Running as root
   sudo $0 $@
   exit
fi


NAME=$1
DIR=/cluster/nodes/$NAME
if [[ -z "$NAME" || ! -d $DIR ]]; then
	echo "Please provide a valid node image name"
	exit 1
fi

cd $DIR
docker build --progress=plain -t temp .

docker remove temp || true
docker run -it --name temp temp sleep 0
rm -rf rootfs || true
mkdir rootfs
cd rootfs
docker export temp | tar -x
docker remove temp

cp -a /etc/ssh/ssh_host_rsa* etc/ssh/
chmod 600 etc/ssh/ssh_host*key
cat /root/.ssh/*.pub > root/.ssh/authorized_keys

cd ..
ln -sf rootfs/boot/vmlinuz* kernel
ln -sf rootfs/boot/init*.img initrd


