#!/usr/bin/perl

use strict;
use warnings;
use Newton;
use Getopt::Long;

my $basedir = Newton::basedir();

my ($name, $nodeset, $default);
my $ok = GetOptions(
  'name|node=s' => \$name,
  'nodeset=s' => \$nodeset,
  'default' => \$default,
  );

unless($ok and (defined $name or defined $nodeset or defined $default)){
  die "Usage: $0 [ --name <name> | --nodeset <nodeset> | --default] [<role>] [<variant>]\n"
  }

my ($role, $variant) = @ARGV;
$variant ||= 'base';

my $db = Newton::db();

my $where = defined $name ? "name='$name'" : "nodeset='$nodeset'";

if(not defined $role){
  my $roles = $db->selectall_arrayref(
    "SELECT name,role FROM addresses WHERE $where",
    );
  for(@$roles){
    my ($name, $role) = @$_;
    print "Role for $name is $role\n";
    }
  exit;
  }

die "Role $role is not available.\n"
  unless -e "$basedir/nodes/$role/images/$variant/config.ipxe";

die "Node specification does not exist.\n"
  unless $db->do("UPDATE addresses SET role=? WHERE $where", undef, "$role/$variant") > 0;

Newton::node_install_pxe();

