#!/bin/sh 

sudo chmod -R g+w,g+r /newton/
sudo chown -R root.admin /newton/
svn st /newton/ | grep '?' | awk '{print $2}' | xargs -r svn add > /dev/null
svn st /newton/
read -p "Change: " change
svn ci /newton/ -m "$change"

