#!/usr/bin/perl

use strict;
use warnings;
use lib '/newton/scripts/';
use Newton;

my $loginserver = 'login.newton.utk.edu';
my $base = '/lustre/projects';

unless($ENV{USER} eq 'root'){
  die "Error: Must run this as root.\n";
  }

my ($dir, $user) = @ARGV;
help() unless defined $user;

help("Invalid directory name\n") unless $dir =~ /^\w+$/;

my $dirtest = Newton::ssh("test -d $base/$dir && echo Exists", $loginserver);
help("Directory already exists.\n") if $dirtest =~ 'Exists';

my $usertest = Newton::ssh("id $user", $loginserver);
help("Invalid user\n")  unless $usertest =~ /\($user\)/;
my ($group) = $usertest =~ /gid=\d+\((\w+)\)/;
help("No group found for user $user\n") unless defined $group;

print Newton::ssh("mkdir $base/$dir", $loginserver);
print Newton::ssh("chown $user:$group $base/$dir", $loginserver);
print Newton::ssh("chmod 700 $base/$dir", $loginserver);

##################################################################################

sub help {
  my $msg = shift;
  warn $msg if defined $msg;
  die "Usage: $0 <directory> <user>\n"
  }

