#!/usr/bin/perl
# Create IP addresses for Infiniband 

use strict;
use warnings;
use lib "/newton/scripts";
use Newton;
use Data::Dumper;

die "Error: Must provide at least one host name.\n" unless @ARGV;

my $db = Newton::db();

for(@ARGV){
  my ($name, $ip_n) = $db->selectrow_array('SELECT name,ip FROM addresses WHERE name=?', undef, $_);
  my $ip = Newton::ipaddr($ip_n);
  my @oct = split(/\./, $ip);
  splice(@oct, 0, 2, 192, 168);
  my $ibip = join('.', @oct);
  my $ibip_n = Newton::addr2i($ibip);
  my ($basename) = $name =~ /^([^\.]+)\..+$/;
  my $ibname = "$basename.ib";
  next if $db->selectrow_array('SELECT * FROM addresses WHERE name=?', undef, $ibname);
  print "Creating infiniband address $ibip ($ibname) for $name\n";
  $db->do('INSERT INTO addresses (name, ip, type, system) VALUES (?,?,?,?)', 
    undef, $ibname, $ibip_n, 'infiniband', $name);
}

