#!/usr/bin/perl

use strict;
use warnings;
use lib '/newton/scripts';
use Newton;

my ($user, $storage, $cap) = (@ARGV,'','','');
my ($uid, $gid) = Newton::userinfo($user, 'uid','gid');
error("No such user $user.") unless $uid and $gid;
error("Bad storage name: $storage") unless $storage =~ /^[\w\-]+$/;
$cap =~ tr/a-z/A-Z/;
error("Incorrect capacity format: $cap") unless $cap =~ /^\d+\.*\d*(M|G|T)$/;
my $cmd = qq[zfs create main/$storage;zfs set quota=$cap main/$storage;zfs set reservation=$cap main/$storage;chown $uid:$gid /main/$storage;zfs list main/$storage];
print "SSH to thumper to create storage dir.\n";
system("sudo ssh thumper.local '$cmd'");

sub error {
  my $msg = shift;
  die qq/Error: $msg
Usage: create_storage <user> <storage name> <capacity>
/;
  }
