#!/usr/bin/perl

use strict;
use warnings;
use lib '/newton/scripts/';
use Newton;
use Getopt::Long;
use Data::Dumper;

unless($ENV{USER} eq 'root'){
  die "Error: Must run this as root.\n";
  }

my $name = shift @ARGV;
help() unless defined $name;

my $db = Newton::db();
my ($test, $server, $mntpnt) = $db->selectrow_array(
  'SELECT name,server,mntPnt FROM storage WHERE name=?', undef, $name,
  );
help("Error: No such NFS share found.\n") unless defined $test;

print "Deleting share '$name' from the database.\n";
print "You must now do the following on server $server:\n";
print " - Delete '$name' from /etc/fstab and /etc/exports\n";
print " - Run 'exportfs -r'.\n";
print " - Unmount $mntpnt and rmdir $mntpnt.\n";
print " - Delete the logical volume for '$name'.\n";

my $db_ok = $db->do('DELETE FROM storage WHERE name=?', undef, $name);
help("Error writing to the database.\n") unless $db_ok;

`/newton/scripts/rebuild_autofs`;

##################################################################################

sub help {
  my $msg = shift;
  warn $msg if defined $msg;
  die "Usage: $0 <shareName>\n"
  }

sub ssh {
  warn @_;
  return Newton::ssh(@_, $server, '-');
  }

