#!/bin/bash -e

# Don't remove images that are currently in use by a node or
# are the newest image for each node TYPE

BASEDIR=$(cluster_basedir)

ACTIVE=`runall -rl 'stat -c "%i" /' | awk '{print $2}' | sort -u`

CURRENT=`stat -c '%i' $BASEDIR/nodes/*/images/*/rootfs/`

for image in `ls -d $BASEDIR/nodes/*/images/*/rootfs-*`; do
   image_inode=`stat -c '%i' $image`
   for active_inode in $ACTIVE; do
      [ $image_inode = $active_inode ] && echo Ignoring active $image && continue 2
   done
   for active_inode in $CURRENT; do
      [ $image_inode = $active_inode ] && echo Ignoring current $image && continue 2
   done
   echo Removing $image
   #read -p "Remove image $image?"
   rm -rf $image
done

