#!/bin/bash -e

if [ $USER != "root" ]; then
   echo Running as root
   sudo -i $0 $@
   exit
fi

runall -rl 'find / -maxdepth 1 -type f -size 0' 

ACTIVE=`runall -rl 'stat -c "%i" /' | awk '{print $2}' | sort -u`

CURRENT=`stat -c '%i' /cluster/nodes/*/images/*/rootfs/`

for image in `ls -d /cluster/nodes/*/images/*/rootfs-*`; do
   image_inode=`stat -c '%i' $image`
   for active_inode in $ACTIVE $CURRENT; do
      [ $image_inode = $active_inode ] && continue 2
   done
   read -p "Remove image $image?"
   rm -rf $image
done

