#!/usr/bin/perl
# Given a list of nodes, shows users having at least one job on each.
# Used for finding problem sources.

use strict;
use warnings;
use Newton;
use Data::Dumper;

my @nodes = @ARGV;
die unless @nodes;
my %total;
for(@nodes){
  my $node = $_;
  my @jobs = Newton::joblist('-u \* -s r -g t -q \*@'.$node);
  my %temp;
  for(@jobs){
    my $user = $_->{JB_owner};
    $total{$user} ++ unless $temp{$user}++;
    }
  }

for(keys %total){
  print "$_\n" if $total{$_} == @nodes;
  }


