#!/usr/bin/perl
# monitor messages log for puppetca clean requests

use strict;
use warnings;
use POSIX;
use Sys::Syslog;

$ENV{PATH} = '/bin:/usr/bin:/sbin:/usr/sbin';

open(SM, "+> /var/lock/subsys/pmonitor") or die $!;
die "Arleady running.\n" unless flock(SM, 6);


        $SIG{CHLD} = 'IGNORE';
        my $pid = fork;
        exit if $pid;
        POSIX::setsid();
        close(STDOUT);
        close(STDERR);
        close(STDIN);

$SIG{INT} = 'quit';

openlog("puppetca", "nofatal");
syslog('info', "Starting up puppetca_monitor.");

open(LOG, "/usr/bin/tail -F /var/log/messages |") or die $!;
while(<LOG>){
  chomp;
  if(/'puppetca --clean ([\w\.\-]+)'/){
    my $node = $1;
    syslog('info', "Cleaning out certificate for $node.");
    `/usr/sbin/puppetca --clean $node`;
    }
  elsif(/ ([\w\.\-]+) has a waiting certificate request/ 
      or /Allowing unauthenticated client ([\w\.\-]+)/){
    my $node = $1;
    syslog('info', "Signing certificate for $node.");
    `/usr/sbin/puppetca --sign $node`;
    }
  }
close LOG;
closelog;

sub quit {
  close LOG;
  closelog;
  }
