#!/usr/bin/perl
# Rebuild autofs NIS maps

use strict;
use warnings;
use lib '/newton/scripts';
use Newton;

my $outfile = '/newton/files/nis/auto.data';
my $db = Newton::db();
my $mounts = $db->selectall_arrayref(
  'SELECT name,mntOpt,server,mntPnt FROM storage ORDER BY name DESC'
  );

open(DAT, "+> $outfile") or die $!;
flock(DAT, 2) or die $!;
print DAT "# Automatically created with /newton/scripts/rebuild_autofs\n";
for(@$mounts){
  my ($name,$mntopt,$server,$mntpnt) = @$_;
  $server = '' unless defined $server;
  $mntopt = '' unless defined $mntopt;
  print DAT "$name $mntopt $server:$mntpnt\n";
  }
close DAT;


warn "SUDO to update NIS maps.\n" unless $ENV{USER} eq 'root';
print `cd /var/yp && sudo make`;


