#!/usr/bin/perl
#
# This script will take a number of C6100 systems (which each contain 4 sub-systems)
# and will rename the machines so that sub-systems in the same chassis will have the
# same name prefix.
#
use strict;
use warnings;
use Newton;

my $nodeset = shift @ARGV;

die "not updated to use new DB schema";
my $db = Newton::db();
my $nodes = $db->selectall_arrayref(
  'SELECT name,ip,domain FROM nodes where nodeset=?',
  undef, $nodeset,
  );
my (%h, %s, $c);
my @alpha = qw(a b c d);
for(@$nodes){
  my ($name, $ip, $domain) = @$_;
  my $info = Newton::ssh('dmidecode -s system-serial-number', $ip, '-');
  if(not defined $info){
    print "Couldn't ssh to $name $ip\n";
    next;
    }
  chomp $info;
  $h{$info}=$c++ unless $s{$info}++;
  next if $name =~ /[a-z]\.\w+$/; # already been renamed
  my $newname = sprintf('%s%02i%s.%s', $nodeset, $h{$info}, $alpha[$s{$info}-1], $domain);
  $db->do('UPDATE nodes SET name=? WHERE name=?', undef, $newname, $name);
  print "$name -> $newname\n";
  }


$db->disconnect();

