#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;
use lib "/newton/scripts";
use Newton;

Getopt::Long::Configure("bundling");
my %opt;
my $ok = GetOptions(
	\%opt,
	'type|t=s',
	'nodes|n=s',
	'pe=n',
	'help|h',
	);

my $batchfile = shift @ARGV;
if(not $ok or not defined $batchfile or $opt{help}){
  help();
  }
if(not $opt{pe} or $opt{pe} !~ /^\d+$/){
  die "Option 'pe' incorrect.\n";
  }
unless(-e $batchfile){
  die "Batch file '$batchfile' is not accessible.\n";
  }

my $nodes = Newton::nodes(%opt);
for(@$nodes){
  my ($node) = @$_;
  print `qsub -q \\*\@$node -pe threads $opt{pe} $batchfile`;
  }

sub help {
        print <<End
This program runs a given command on every node in the cluster.
Usage:  runall [option] <command>

Options include:
	-t, --type     - Type of machine to run on (pxe config file name)
	--pe <int>     - Number of processors on each machine.
	-n, --nodes    - String or regex that describes the subset of node 
                         names to run on.
	--help         - Show this message
End
;
        exit;
        }

