
- name: Uninstall podman
  yum: name=podman-docker state=absent

- name: Install Docker-ce yum repo
  copy: src=docker-ce.repo dest=/etc/yum.repos.d/

- name: Install Docker 
  yum:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Remove docker group (is provided by ipa/ldap)
  group: name=docker local=yes state=absent

- name: Enable docker service
  service: name=docker state=started enabled=yes

- name : Cron to periodically clean up docker objects
  cron:
    name: "docker"
    job: "docker system prune -f > /dev/null"
    minute: 1
    hour: "1"

