
- name: Uninstall podman
  yum: name=podman-docker state=absent

- name: Install Docker-ce yum repo
  copy: src=docker-ce.repo dest=/etc/yum.repos.d/

- name: Install Docker 
  yum:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Remove docker group (is provided by ipa/ldap)
  group: name=docker local=yes state=absent

- name: Setup docker daemon config
  copy: src=daemon.json dest=/etc/docker/

- name: Enable docker service
  service: name=docker state=started enabled=yes

