- hosts: localhost
  remote_user: root
  roles:
          - firewall
          - headnode
          - dnsmasq
          - nfs-server
          - slurm
          - nat
          - docker
          - ganglia-gmond
          - nrpe
