- hosts: all:!dev:!saturn.icl.utk.edu
  remote_user: root
  roles:
          #- OSupdate
          - inventory
          - sshd
          - ipa-client
          - all
          - role: ganglia-gmond
            when: (ansible_os_family == "RedHat") and (ansible_distribution_major_version < '8')

- hosts: all:!dev:!rhel8
  remote_user: root
  roles:
          - fail2ban
          - nrpe

- hosts: omega0.icl.utk.edu omega1.icl.utk.edu omega2.icl.utk.edu backup.icl.utk.edu xylitol.icl.utk.edu
  remote_user: root
  roles:
    - openmanage

- hosts: backup.icl.utk.edu
  remote_user: root
  roles:
      - backup
      - zfs

- hosts: redhatResearch
  remote_user: root
  roles:
          - reinstall
          - ofed
          - perf_mods
          - autoupdate
          - research
          - docker-ns

- hosts: all:!ash2.icl.utk.edu:!venus.icl.utk.edu:!dev:!tellico:!ubuntu:!saturn.icl.utk.edu
  remote_user: root
  roles:
          - firewall

#### Machine-specific configs ####

- hosts: sorbitol.icl.utk.edu
  remote_user: root
  roles:
          - docker_headnode

- hosts: histamine2.icl.utk.edu
  remote_user: root
  roles:
          - cuda
          - docker
          - rocm

- hosts: histamine
  remote_user: root
  roles:
          - histamine

- hosts: lips.icl.utk.edu xsdk.icl.utk.edu methane.icl.utk.edu morphine.icl.utk.edu leconte.icl.utk.edu
  remote_user: root
  roles:
          - cuda
          - docker

- hosts: leconte.icl.utk.edu 
  remote_user: root
  roles:
          - dgx
          - rocm

- hosts: guyot.icl.utk.edu
  remote_user: root
  roles:
          - dgxa100

- hosts: lips.icl.utk.edu phi.icl.utk.edu caffeine.icl.utk.edu xsdk.icl.utk.edu
  remote_user: root
  roles:
          - docker-ns

- hosts: radeon
  remote_user: root
  roles:
          - rocm

- hosts: deimos.icl.utk.edu phobos.icl.utk.edu methanol.icl.utk.edu harry.icl.utk.edu
  remote_user: root
  roles:
          - knl_mods
          - kernel

- hosts: omega0.icl.utk.edu 
  remote_user: root
  roles:
          - nfs-server

- hosts: admin.icl.utk.edu
  remote_user: root
  roles:
        - admin-web
        - nagios
        - ganglia-web
        - docker

- hosts: xylitol.icl.utk.edu
  remote_user: root
  roles:
        - jenkins-web

- hosts: phi.icl.utk.edu
  remote_user: root
  vars:
    gmond_conf: "gmond-phi.conf" 
  roles:
        - headnode
        - ganglia-gmetad  

- hosts: headnode-dev
  remote_user: root
  roles:
          - headnode-dev

- hosts: tellico
  remote_user: root
  roles:
        - tellico
        - perf_mods

- hosts: web.icl.utk.edu
  remote_user: root
  roles:
        - webserver
        - php
        - database

