- hosts: sorbitol.icl.utk.edu
  remote_user: root
  roles:
          - firewall
          - headnode
          - dnsmasq
          - nfs-server
          - slurm
          - nat
          - docker
          - ipa-client
          - ganglia-gmond
          - zfs
          - nrpe
