- name: Install fail2ban
  yum: name=fail2ban

- name: Create log file
  file: path=/var/log/fail2ban.log state=touch

- name: Configure jail.local
  copy: src=jail.local dest=/etc/fail2ban/jail.local
  notify: "Restart fail2ban"

- name: Configure fail2ban.local
  copy: src=fail2ban.local dest=/etc/fail2ban/fail2ban.local
  notify: "Restart fail2ban"

- name: Enable fail2ban
  service: name=fail2ban state=started enabled=yes

