- name: Restart network
  service: name=NetworkManager state=restarted

- name: Restart rsyslog
  service: name=rsyslog state=restarted

- name: Restart chronyd
  service: name=chronyd state=restarted

- name: Set hostname
  command: hostname `cat /etc/hostname`

