- name: Script file for implementing system modifications on KNL
  copy: src=knl_mods.sh dest=/opt/knl_mods.sh mode=755
- name: Cron to implement KNL system changes on boot
  cron: 
    name: "KNL modifications"
    job: "/opt/knl_mods.sh"
    special_time: reboot

- name : Cron to implement KNL system changes periodically
  cron:
    name: "KNL modifications periodic"
    job: "/opt/knl_mods.sh"
    minute: 1
    hour: "*"

- name: Install Performance Co-pilot
  yum: name=pcp state=installed

- name: Enable PCP service
  service: name=pmcd state=started enabled=yes

