
- name: Enable the firewall
  service: name=firewalld state=started enabled=yes

- name: Set the ICL network source
  firewalld: zone=internal source=160.36.131.0/24  permanent=true state=enabled immediate=true

- name: Add phi cluster to ICL internal network zone
  firewalld: zone=internal source=160.36.179.212  permanent=true state=enabled immediate=true

- name: Add data backup system to ICL internal network zone
  firewalld: zone=internal source=160.36.179.232  permanent=true state=enabled immediate=true

- name: Add web.icl.utk.edu VM to ICL internal network zone
  firewalld: zone=internal source=160.36.179.155  permanent=true state=enabled immediate=true

- name: Create firewall zone for UT networks
  shell: firewall-cmd --new-zone=utk --permanent && firewall-cmd --reload
  args:
    creates: /etc/firewalld/zones/utk.xml

- name: Add UTK networks
  firewalld: zone=utk source={{ item }} state=enabled permanent=true immediate=true
  with_items:
          - 160.36.0.0/16
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/12
          - 216.96.128.0/17

- name: Allow SSH from UTK
  firewalld: zone=utk service=ssh state=enabled permanent=true immediate=true

