#!/bin/bash -e

function get_variants(){
TOP=$1
DIR=$1
MODULENAME=$2

while [[ $DIR != "/" && ! -e $DIR/share/spack/setup-env.sh ]]; do
  DIR=`dirname $DIR`
done

if [ -f $DIR/share/spack/setup-env.sh ]; then
   source $DIR/share/spack/setup-env.sh
   spack find -x --format '{name}/{version}/{compiler}-{hash:4}   {variants}' $MODULENAME | sed -e 's/@/-/'
else
   export MODULEPATH=$TOP
   module avail $MODULENAME
fi
}

modulename=$1

for path in ${MODULEPATH//:/ }; do
  get_variants $path $modulename
done
