- include_role: name=webserver
- include_role: name=firewall

#- name: Copy website files
#  copy: src=html/ dest=/var/www/html/ mode=preserve
#  notify: "Restart Apache"

- name: Disable SSH on public zone
  firewalld: service=ssh zone=public state=disabled permanent=true immediate=true


