#!/usr/bin/perl

# Warn when the ambient temperature reaches a given point

use strict;
use warnings;
use lib '/usr/lib64/nagios/plugins';
use utils '%ERRORS';

my $sensor = 'Temp_Ambient_FP';
my $warn_temperature = 27;

my ($temperature) = `ipmitool sensor get "$sensor"` =~ /Reading\s+: (\d+)/s;

finish('WARNING', "No reading") unless defined $temperature;
finish('OK', "$temperature C") if $temperature < $warn_temperature;
finish('CRITICAL', "$temperature C!");

sub finish {
  my ($code, $msg) = @_;
  print "Ambient temperature $code: $msg\n";
  exit $ERRORS{$code};
  }
